### ISSUE TITLE
Version 1.2 causes Activity Indicator to disappear

### ISSUE THREAD

**Issue by BlohoJo** [Noitidart/Throbber-Restored#11]
When I install the Throbber Restored 1.2 update, my Throbber Restored Activity Indicator disappears. It is not available on the View -> Toolbars -> Customize screen. When I downgrade to version 1.1, it reappears.

I have Firefox 30 and I am using Classic Theme Restorer. I never had any issues with Throbber Restored and Classic Theme Restorer.

Attached is a screenshot of my customized Firefox. The Throbber Restored Activity Indicator is in the lower left corner. It will disappear if I update to 1.2, and reappear if I downgrade to 1.1.

![throbberrestored](https://cloud.githubusercontent.com/assets/8242464/3669008/c8d1e6de-122a-11e4-9ae5-998efe33e3fe.png)

**Comment by BlohoJo** [comment]
I just tried removing the Throbber Restored 1.1 Activity Indicator from the lower left, so it's listed back in the toolbar buttons. I then installed the 1.2 Throbber Restored update. When I checked back on the View -> Toolbars -> Customize screen, I found that the Throbber Restored Activity Indicator once again disappeared from the toolbar buttons, with seemingly no way to add it back, other than to downgrade to version 1.1

**Comment by Noitidart** [comment]
Thanks for the report man. Can you try restarting your browser after install v1.2 I had to change the ID because v1.1 was conflicing with the add-on "Classic Theme Restorer".

**Comment by BlohoJo** [comment]
I apologize, I forgot to mention, I did restart the browser in both instances. It had no effect on the problem.

**Comment by Noitidart** [comment]
No apology man, I appreicate you taking the time to try to get this fixed.

Interesting. I'll look into this.

**Comment by yajd** [comment]
Hey man I'm not able to recreate this error. Can you please think of other things that may be cuasing this issue?

It's weird because 2 other users are having this problem but i can't resimulate.

Would it be possible for me to connect to your computer with TeamViewer? (Last resort) 

this is noit from my school account

**Comment by Noitidart** [comment]
Or if you're more comfortable can you please download TeamViewer and then connect to me and recreate the issue on my system please.

**Comment by BlohoJo** [comment]
Try this...

Here is my profile, minus the bookmarks and any password / form / cache data:

http://tommycatkins.com/2014/etfnhvmo.default.rar

The RAR password is throbber_tshoot_6RJB

I'm using Firefox 30 under XP.

If you can use the profile manager to create a new profile, then dump my profile into the new profile folder, you should have my setup. See if the problem then occurs for you. It has Throbber Restored at 1.1, try upgrading it to 1.2 and see if the issue occurs (throbber in lower left corner disappears).

**Comment by Noitidart** [comment]
Thanks man very much. I'll try it out. If not work Ill let you know please. Would you have sometime to connect to my computer please? I got the file downloaded btw, so you can delete from your host. Thanks man.

**Comment by Noitidart** [comment]
It worked!! Thanks man i replicated the bug. Ok ill get to work on this and fix momentarily thanks man for your hard work.

**Comment by BlohoJo** [comment]
I deleted the profile, please let me know if you need to download it again for any reason. ;)

**Comment by Noitidart** [comment]
Thanks man. Ok I can't figure this bug out, it is so so weird. I temporarily fixed it by changing the id back to `navigator-throbber` but i dont want to release it till i figure out what caused that bug.

But please install and test this for me please:
https://github.com/yajd/Throbber-Restored-1/tree/patch-1

Can install from the repo by using github extension installer: https://addons.mozilla.org/en-US/firefox/addon/github-extension-installer/

i posted on stackoverflow for help, it is unbelievable i cant figure why a id change could fix this issue, it shouldnt have any affect

**Comment by BlohoJo** [comment]
OK, I installed the test version from https://github.com/yajd/Throbber-Restored-1/tree/patch-1, and it appears to work OK so far!

**Comment by Noitidart** [comment]
Hey man can you please try to install  from this repo here:

But first: Please install v1.1 then install v1.2 from amo and see if it has the problem. Get it to disappear. Then install from here please:
https://github.com/Noitidart/Throbber-Restored/tree/442c8642a5ba9281357ec34ed687c616bf942d1e

I think this might have the fix.

**Comment by BlohoJo** [comment]
Sorry, it didn't work.

Here's what I did:

1) Install Throbber Restored 1.1 from addons.mozilla.org. Throbber is there.

2) Restart. Throbber is still there.

3) Install Throbber Restored 1.2 update from addons.mozilla.org. Throbber is gone.

4) Restart. Throbber is still gone.

5) Manually install https://github.com/Noitidart/Throbber-Restored/tree/442c8642a5ba9281357ec34ed687c616bf942d1e. Throbber is still gone.

6) Restart. Throbber is still gone.

7) Manually install https://github.com/yajd/Throbber-Restored-1/tree/patch-1. Throbber is there.

8) Restart. Throbber is still there.

:\

**Comment by Noitidart** [comment]
Aw dang. Thanks for the detailed break down of the test that helps!

**Comment by click-click** [comment]
> I had to change the ID because v1.1 was conflicing with the add-on "Classic Theme Restorer".

What conflict are you talking about? I used CTR from the start and Throbber 1.1 never caused any problems  with CTR for me.  Only after installing 1,2. Maybe the old ID  is somehow linked to CTR after the first time Throbber 1.1 was installed and now there is a conflict in CTR with the new ID which is causing the problem.  Anyone that starts of with Throbber 1.2 as the initial install would not see this problem.
Just a guess though. If you have it working with 1.2 try downgrading to  1.1 and see if the throbber disappears. That might shed some light on things.

**Comment by Noitidart** [comment]
Thanks click-click I think you are very right about if people use 1.2 as the initial install. I'm going to try to resolve this so that people with 1.2 as initial install won't have a problem with 1.3.

**Comment by Noitidart** [comment]
I'm not sure click-click about the conflict. Some people were complaining that to install v1.0 they had to first disable CTR then install throbber restored then re-eanble CTR, i could never replicate the issue.

**Comment by Noitidart** [comment]
hey man this took me months but i think i fixed it. please test from here:

https://github.com/Noitidart/Throbber-Restored/tree/09b3d99894eb2bbcd240e5676a61f44784cc62d2

forgive the insane delay plz

**Comment by click-click** [comment]
Is there an xpi anywhere? Not sure what to test from those files

**Comment by TryMedian** [comment]
I've used your v 1.1 for quite a while, and it's perfect for me.  I tried your latest version, but it doesn't work for me.  Upon restarting Firefox, the throbber was gone.  In toolbox/customize I moved the activity monitor icon to the toolbar, selected my static and loading .gif files, but no throbber.  I noticed that if I went back to your prefs, the .gif locations were empty.  I did not try the disable/re-enable CTR trick, since I think that's what you were trying to avoid in v 1.2.

I reverted to your v 1.1 and all was well.  For me, v 1.1 is a perfect and indispensable add-on.  My set-up:  Mac OS X 10.6.8, Firefox 33.1, CTR 1.2.6.1.

**Comment by Noitidart** [comment]
Thanks TryMedian, yep that disable/renabled CTR thing was what I was trying to fix.

Please try v1.3 @click-click and @TryMedian https://addons.mozilla.org/en-US/firefox/addon/throbber-restored/versions/

**Comment by TryMedian** [comment]
Sorry, still does not work.  The image locations disappear even if you just reload your prefs in about:addons.  That does not happen for v 1.1.  In case this helps: I use some small Stylish code to provide a dark background for the Loading image.  Basically, 

#navigator-throbber[loading] { background-color: #22f !important; }

When a page is loading, I do see the dark square background, just no image in the foreground.

**Comment by Noitidart** [comment]
Thanks very much for the test and feedback @TryMedian I'll try to fix this right away. Do you have time to chat on mozilla extdev irc channel by any chance? https://client00.chat.mibbit.com/?url=irc%3A%2F%2Firc.mozilla.org%2F%23extdev

**Comment by Noitidart** [comment]
Oh @click-click  and @TryMedian after install v1.3 please check your customize panel. `about:customizing` to see if the throbber got moved into there.

**Comment by Noitidart** [comment]
Accidental close there. Whoops. Re-opened it.

**Comment by TryMedian** [comment]
I tried a few more perturbations.

In v 1.1, the customize panel includes
![1 1](https://cloud.githubusercontent.com/assets/9996247/5237197/f9f965b6-7841-11e4-835f-5daad86cbe33.png)
and all is well.

If I then install v 1.3, the activity indicator is there, but blank:
![1 3](https://cloud.githubusercontent.com/assets/9996247/5237176/f419858c-7840-11e4-8b96-6393dbb59c52.png)
Moving it to the toolbar, it's still blank.  I re-selected the image locations, still blank.  The location won't stick in your prefs.

Then I Removed v 1.3 from the Add-ons Manager page, and restarted Firefox.  I did a fresh install of 1.3, and now everything works as it did in v 1.1.

Note CTR was active throughout.  So, installing 1.3 over 1.1 creates a problem, as if something is remaining from 1.1 and causing a conflict?

**Comment by Noitidart** [comment]
Oh!! Thank you TryMedian!! Yes I think I know what causes it when install over v1.1 excellent feedback! Let me knock something up and post here.

Thanks @TryMedian !

**Comment by click-click** [comment]
!.3 still has the same problem as 1.2 if you install on top of 1.1. If you uninstall 1.3 and then re-install it, the throbber works fine as mentioned above. Is it possible to have the installer just remove the older version before installing the new one and at the same time keep the throbber image that was used previously?

**Comment by Noitidart** [comment]
@click-click yep that's what I'm going trying to detect and do :)

**Comment by Noitidart** [comment]
Hey @click-click and @TryMedian 

please try installing this version over v1.1 and v1.2:
1. Please install addon GitHub Extension Installer: https://addons.mozilla.org/en-US/firefox/addon/github-extension-installer/
2. Install v1.1
3. Go to fixed dev version repo here: https://github.com/Noitidart/Throbber-Restored/tree/708586ef02970319b93a09ec1936e8d81b8f6cbb
4. Click on "Add to Firefox", this install this version to your Firefox,

Let me know if it installs fine please :) Please repeat test for v1.2 :)

**Comment by TryMedian** [comment]
OK, works for me.  I installed 1.1, throbber is fine.  Installed 1.3 over 1.1, still fine.  Installed 1.2 over 1.3, no throbber.  Restart, install 1.3 over 1.2, throbber works.

Small non-functional difference: in 1.1 prefs, the image locations are shown; in 1.3 prefs, the actual images are shown.  Might be useful to show both the images and the locations?

I predict you will sleep well tonight ;)

**Comment by Noitidart** [comment]
Yesss thanks @TryMedian haha :)

About thej not showing path anymore, its because people would set a path for the image and then delete the image. Lots of times people paste a url to an image in the file browser and then that downloads the image to the temp folder and uses it. and when suers clear temp files or delete the file on their hardrive they lose the image.

So now the addon use the path only when you browse for it, and after that it copies the image data so it doesnt matter if users delete the original image or clear temp files etc. So theres no path to show :(

Will definitely be able to sleep now thanks haha!

**Comment by TryMedian** [comment]
OK, I see where you now store the images - that's good.  Sleep well!

**Comment by Noitidart** [comment]
Cleaned up dev messages and uploaded v1.4 which has this fix. Finally! haha thanks all for the help!
